# Generated by Django 5.2.4 on 2025-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_contact_consent_given',
            field=models.BooleanField(default=False, verbose_name='Consentement à être contacté'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_data_consent_given',
            field=models.BooleanField(default=False, verbose_name="Consentement à l'utilisation des données"),
        ),
    ]
