# Generated by Django 5.2.4 on 2025-07-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_user_issue_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High')], default='LO', max_length=2),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TD', 'To do'), ('IP', 'In progress'), ('FI', 'Finished')], default='TD', max_length=2),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BU', 'Bug'), ('TA', 'Task'), ('FE', 'Feature')], default='TA', max_length=2),
        ),
    ]
