# Generated by Django 5.2.4 on 2025-07-30 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_priority_alter_issue_status_alter_issue_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
