# Generated by Django 5.2.4 on 2025-07-30 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
