# Generated by Django 5.2.4 on 2025-07-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='user',
            new_name='author',
        ),
    ]
