# Generated by Django 5.2.4 on 2025-07-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'Back-end'), ('FE', 'Front-end'), ('IO', 'iOS'), ('AN', 'Android')], default='BE', max_length=2),
        ),
    ]
