# Generated by Django 5.2.4 on 2025-07-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='project_type',
        ),
    ]
