# Generated by Django 5.2.4 on 2025-07-30 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
